# config/__init__.py
from .config import (
    BIN_FOLDER, EXE_FOLDER, LUA_FOLDER, THEME_FOLDER, BAT_FOLDER, LISTS_FOLDER,
    LOGS_FOLDER, WINWS_EXE, WINWS2_EXE, ICON_PATH, ICON_TEST_PATH, OTHER_PATH,
    OTHER_BASE_PATH, OTHER_USER_PATH,
    NETROGAT_PATH, NETROGAT2_PATH, STRATEGIES_FOLDER, WIDTH, HEIGHT,
    MIN_WIDTH, MIN_HEIGHT,
    INDEXJSON_FOLDER, WINDIVERT_FILTER,
    MAX_LOG_FILES, MAX_DEBUG_LOG_FILES, MAIN_DIRECTORY, HELP_FOLDER, APP_CORE_PATH,
    APPDATA_DIR,
    # Пути реестра
    REGISTRY_PATH, REGISTRY_PATH_GUI,
    REGISTRY_PATH_STRATEGIES, REGISTRY_PATH_WINDOW,
    # Функции окна
    get_window_position, set_window_position, get_window_size, set_window_size,
    get_window_maximized, set_window_maximized,
    # Функции определения exe по методу
    ZAPRET2_MODES, get_winws_exe_for_method, is_zapret2_mode,
    # Paths for per-user presets/lists templates
    get_zapret_presets_v2_dir, get_zapret_userdata_dir, get_zapret_channel_dir_name, get_zapret_presets_v2_template_dir,
    get_zapret_presets_v1_template_dir,
    get_zapret_lists_template_dir, get_other_template_path,
    get_zapret_lists_backup_dir, get_other_backup_path, get_other_user_backup_path
)
from .build_info import APP_VERSION, CHANNEL
from .reg import reg, HKCU, get_dpi_autostart, set_dpi_autostart, get_subscription_check_interval, get_remove_github_api, get_active_hosts_domains, set_active_hosts_domains, get_auto_update_enabled, set_auto_update_enabled, get_tray_hint_shown, set_tray_hint_shown

__all__ = [
    # build_info.py
    'APP_VERSION',
    'CHANNEL',
    # config.py - папки
    'THEME_FOLDER',
    'EXE_FOLDER',
    'BIN_FOLDER',
    'LUA_FOLDER',
    'BAT_FOLDER',
    'LISTS_FOLDER',
    'LOGS_FOLDER',
    'INDEXJSON_FOLDER',
    'WINDIVERT_FILTER',
    'MAIN_DIRECTORY',
    'HELP_FOLDER',
    'APP_CORE_PATH',
    'APPDATA_DIR',
    'get_zapret_channel_dir_name',
    'get_zapret_userdata_dir',
    'get_zapret_presets_v2_dir',
    'get_zapret_presets_v2_template_dir',
    'get_zapret_presets_v1_template_dir',
    'get_zapret_lists_template_dir',
    'get_other_template_path',
    'get_zapret_lists_backup_dir',
    'get_other_backup_path',
    'get_other_user_backup_path',
    # config.py - пути реестра
    'REGISTRY_PATH',
    'REGISTRY_PATH_GUI',
    'REGISTRY_PATH_STRATEGIES',
    'REGISTRY_PATH_WINDOW',
    # config.py - остальное
    'WINWS_EXE',
    'WINWS2_EXE',
    'ZAPRET2_MODES',
    'get_winws_exe_for_method',
    'is_zapret2_mode',
    'ICON_PATH',
    'ICON_TEST_PATH',
    'OTHER_PATH',
    'OTHER_BASE_PATH',
    'OTHER_USER_PATH',
    'NETROGAT_PATH',
    'NETROGAT2_PATH',
    'STRATEGIES_FOLDER',
    'MAX_LOG_FILES',
    'MAX_DEBUG_LOG_FILES',
    'WIDTH',
    'HEIGHT',
    'MIN_WIDTH',
    'MIN_HEIGHT',
    # reg.py
    'get_dpi_autostart',
    'set_dpi_autostart',
    'get_subscription_check_interval',
    'get_remove_github_api',
    'get_active_hosts_domains',
    'set_active_hosts_domains',
    'get_auto_update_enabled',
    'set_auto_update_enabled',
    'get_tray_hint_shown',
    'set_tray_hint_shown',
    'get_window_position',
    'set_window_position',
    'get_window_size',
    'set_window_size',
    'get_window_maximized',
    'set_window_maximized',
    'reg',
    'HKCU'
]
