from __future__ import annotations


PROFILE_DARK_PAGE_BG = "#272727"
PROFILE_ROW_BG_DARK = "#323232"
PROFILE_ROW_BG_DARK_HOVER = "#393939"
PROFILE_BADGE_HOSTLIST_BG = "#6CCB5F"
PROFILE_BADGE_HOSTLIST_FG = "#111814"
PROFILE_BADGE_IPSET_BG = "#8B5CF6"
PROFILE_BADGE_IPSET_FG = "#111114"
PROFILE_STATUS_DOT_ACTIVE = "#6CCB5F"


__all__ = [
    "PROFILE_DARK_PAGE_BG",
    "PROFILE_ROW_BG_DARK",
    "PROFILE_ROW_BG_DARK_HOVER",
    "PROFILE_BADGE_HOSTLIST_BG",
    "PROFILE_BADGE_HOSTLIST_FG",
    "PROFILE_BADGE_IPSET_BG",
    "PROFILE_BADGE_IPSET_FG",
    "PROFILE_STATUS_DOT_ACTIVE",
]
